---
title: "Police Districts"
output: pdf_document
---


```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(ggplot2)
library(ggmap)

data <- read.csv('https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.csv?accessType=DOWNLOAD')

data <- data[!is.na(data$Geolocation) & data$Geolocation!='',]
data$New.Lat <- pmax(data$Latitude, data$Longitude)
data$New.Lon <- pmin(data$Latitude, data$Longitude)
data$Districts = data$SubAgency
levels(data$Districts) = c('Rockville','Bethesda','Silver Spring','Wheaton','Germantown','Gaithersburg','HQ')

alcohol <- data[grepl('ALCOHOL',data$Description),]
```


```{r,echo=FALSE,warning=FALSE,message=FALSE}

##Violation proportions by district
districts = as.data.frame(rbind(cbind(rep('All',7),levels(alcohol$Districts),summary(data$SubAgency)/dim(data)[1]),cbind(rep('Alcohol',7),levels(alcohol$Districts),summary(alcohol$SubAgency)/dim(alcohol)[1])))
colnames(districts) <- c('Group','District','Proportion')

ggplot(districts,aes(x = District,y=as.numeric(Proportion)/100)) + 
  geom_bar(aes(fill=Group),stat = 'identity', position='dodge') + 
  scale_fill_manual(values=c("midnightblue", "slategray2")) + 
  ggtitle('Violations by Police District') + 
  scale_y_continuous(name='Proportion',labels = scales::percent)

```


```{r,echo=FALSE,warning=FALSE,message=FALSE}

map <- get_map(location = c(lon = -77.129074, lat = 39.10359), zoom = 11,maptype='roadmap')

##map of sample (of the same number as alcohol violations) of all violations by district
sample <-data[sample(dim(data)[1],dim(alcohol)[1]),]
ggmap(map,extent = 'device') + 
  geom_point(aes(x=New.Lon, y = New.Lat, color = Districts), alpha = .1, size = 2,data = sample) + 
  guides(colour = guide_legend(override.aes = list(alpha = 1))) + 
  ggtitle('Violations by District')

```


```{r,echo=FALSE,warning=FALSE,message=FALSE}

##map of alcohol violations only
ggmap(map,extent = 'device') + 
  geom_point(aes(x=New.Lon, y = New.Lat, color = Districts), alpha = .1, size = 2,data = alcohol) + 
  guides(colour = guide_legend(override.aes = list(alpha = 1))) + 
  ggtitle('Alcohol Violations by District')

```

